homeless_pets/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using homeless_pets.Models;

namespace homeless_pets.Controllers
{
    public class CatalogController : Controller
    {
        public int pagesize = 4;

        // GET: Catalog
        //public ActionResult List(int page = 1)
        //{
        //    PetsContext pets = new PetsContext();   
        //    return View(pets.Pets);
        //}

        public ActionResult Card(int? id)
        {
            ViewBag.Variable = id;
            PetsContext pets = new PetsContext();
            return View(pets.Pets);
        }

        public ActionResult List(string searchString, string all, string MoveGender = null)
        {
            PetsContext petsConx = new PetsContext();
            var pets = from m in petsConx.Pets
                       select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                pets = pets.Where(s => s.Name.Contains(searchString));
            }

            //ViewBag.SelectedGender = gender;

            if (MoveGender != null && MoveGender != "Выбрать пол")
            {
                pets = pets.Where(s => s.Gender == (MoveGender == "Женский" ? true: false));

            }

            List<SelectListItem> genderItems = new List<SelectListItem>();
            genderItems.Add(new SelectListItem() { Text = "Выбрать пол", Selected = (MoveGender) == null ? true : false });
            genderItems.Add(new SelectListItem() { Text = "Мужской", Value = "Мужской", Selected = (MoveGender) == "Мужской" ? true : false });
            genderItems.Add(new SelectListItem() { Text = "Женский", Value = "Женский", Selected = (MoveGender) == "Женский" ? true : false });
            ViewBag.MoveGender = genderItems;

            return View(pets);
        }
    }
}

homeless_pets/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using homeless_pets.Models;

namespace homeless_pets.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            NewsContext newsConx = new NewsContext();

            var pets = from m in newsConx.News
                       select m;

            return View(pets);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

homeless_pets/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using homeless_pets.Models;

namespace homeless_pets.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ViewResult NewPage(int? id)
        {
            if (id == null)
            {
                return View("NewsRedactor");
            }

            NewsContext news = new NewsContext();
            return View(news.News.FirstOrDefault(n => n.NewID == id));
        }
        //редактировать новости
        public ViewResult EditNews(int? id)
        {
            if (id == null)
            {
                return View("EditNews");
            }
            NewsContext news = new NewsContext();
            //PetsContext pet = PetsContext;
            //pets.Pets.FirstOrDefault(id)
            return View(news.News.FirstOrDefault(n => n.NewID == id));
        }

        public ActionResult NewsRedactor()
        {
            NewsContext news = new NewsContext();
            return View(news.News);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditNews(New newVariable, int? id)
        {
            DBforNewsRedactor BDaction = new DBforNewsRedactor();
            if (ModelState.IsValid)
            {
                BDaction.SaveNew(newVariable);
                TempData["message"] = string.Format("Изменения \"{0}\" были сохранены", newVariable.Header);
                return RedirectToAction("NewsRedactor");
            }
            else
            {
                // Что-то не так со значениями данных
                return View(newVariable);
            }
        }
        //создать новости
        public ViewResult Create()
        {
            return View("EditNews", new New());
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            DBforNewsRedactor BDaction = new DBforNewsRedactor();
            New deletedNew = BDaction.DeleteNew(id);
            if (deletedNew != null)
            {
                TempData["message"] = string.Format(" \"{0}\" была удалена",
                    deletedNew.Header);
            }
            return RedirectToAction("NewsRedactor");
        }
    }
}

homeless_pets/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<main class="container">
    <section id="contacts" class="page">
        <div class="row">
            <div class="col-md-9">
                <div>
                    <p>Мы рады будем вам помочь или получить от вас отзыв по работе объединения, по указаным ниже контактам.</p>
                    <p>Следите за нашими новостями&nbsp;в социальных сетях:</p>
                    <ul>
                        <li><a href="https://www.facebook.com/" target="_blank">Facebook</a></li>
                        <li><a href="https://twitter.com/" target="_blank">Twitter</a></li>
                        <li><a href="https://ok.ru/" target="_blank">Однокласники</a></li>
                        <li><a href="http://vk.com/" target="_blank">Вконтакте</a></li>
                    </ul>
                    <hr>
                    <h4>&nbsp;</h4>
                    <h4>Главный&nbsp;объединения,&nbsp;Матвей Кривицкий:&nbsp;</h4>
                    <p>Контактный телефон:&nbsp;<a href="tel:+375298396736">+375298394736<br></a>E-mail:&nbsp;<a href="">info@examle.by</a></p>
                    <h4>Отдел рекламы:&nbsp;</h4>
                    <p>Контактный телефон: <a href="tel:+375292857206">+375292877206</a><br>E-mail:&nbsp;<a href="">pr@examle.by</a></p>
                    <p>&nbsp;</p>
                    <h4>Координатор по котам:&nbsp;</h4>
                    <p>Контактный&nbsp;телефон:&nbsp;<a href="tel:+375299704760">+375299709760</a>&nbsp<br /><a href="">cat@examle.by</a>&nbsp;</p>
                    <h4>Координатор по собакам:&nbsp;</h4>
                    <p>Контактный телефон:&nbsp;<a href="tel:+375292960486">+375291960486</a>&nbsp;<br>E-mail:&nbsp;<a href="">dog@examle.by</a></p>
                    <p>&nbsp;</p>
                </div>
            </div>
        </div>
    </section>
</main>

homeless_pets/Views/Home/Index.cshtml
@model IEnumerable<homeless_pets.Models.New>
@{
    ViewBag.Title = "Homeless pets";
}
<script src="~/Scripts/jquery-1.10.2.min.js"> </script>
<script type="text/javascript">
    $(document).ready(function () {
    })</script>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->

    <div class="carousel-inner">
        <div class="item active">
            <img src="~/Images/promo1.png" alt="">
            <div class="carousel-caption">
                <h3>Маруся</h3>
                <p>Кошка в дар для ценителей классики. Идеальный котенок для любителей фортепианной музыки. Окрас как у клавишей фоно, музыкальный голос...</p>
                <p>@Html.ActionLink("Каталог \u00BB", "List", "Catalog", null, new { @class = "btn btn-primary btn-lg" })</p>
            </div>
        </div>

        <div class="item">
            <img src="~/Images/promo_2.png" alt="">
            <div class="carousel-caption">
                <h3>Максим</h3>
                <p>Это не кот, а самое настоящее торнадо. Веселый и потешный дурашка. Он постоянно куда-то бежит, что-то хватает, кого-то ловит...</p>
                <p>@Html.ActionLink("Каталог \u00BB", "List", "Catalog", null, new { @class = "btn btn-primary btn-lg" })</p>
            </div>
        </div>

        <div class="item">
            <img src="~/Images/promo_3.png" alt="">
            <div class="carousel-caption">
                <h3>Мирциария</h3>
                <p>Утонченная, гибкая, настоящая ladycat ищет дом. Рожденная на улице, девочка жила в голоде и постоянном страхе...</p>
                <p>@Html.ActionLink("Каталог \u00BB", "List", "Catalog", null, new { @class = "btn btn-primary btn-lg" })</p>
            </div>

        </div>
    </div>
</div>

<div class="row">
    @foreach (var topic in Model)
    {
        <div class="col-md-4">
            <h2>@topic.Header</h2>
            <p>
                @topic.Short
            </p>
            <p>@Html.ActionLink("Читать", "NewPage", "News", new { id = topic.NewID }, new { @class = "btn btn-default" })</p>
        </div>
    }
</div>

<section id="thanks">
    <h3>Спасибо ВСЕМ кто не остался равнодуным!</h3>
    <nav>
        <a href="http://interfax.by" target="_blank"><img src="~/Images/logos/interfax.png" alt="Интерфакс" title="Интерфакс"></a>
        <a href="http://remesla.by" target="_blank"><img src="~/Images/logos/remesla.png" alt="Remesla.by" title="Remesla.by"></a>
        <a href="http://hoster.by" target="_blank"><img src="~/Images/logos/hosterby.png" alt="hoster.by" title="hoster.by"></a>
        <a href="http://zapomnim.by" target="_blank"><img src="~/Images/logos/zapomnim.png" alt="Свеча Памяти" title="Свеча Памяти"></a>
        <a href="http://maesens.by" target="_blank"><img src="~/Images/logos/maesens.png" alt="МаеСэнс" title="МаеСэнс"></a>
        <a href="http://str.by" target="_blank"><img src="~/Images/logos/str.png" alt="Streamline" title="Streamline"></a>
        <a href="http://onliner.by" target="_blank"><img src="~/Images/logos/onliner.png" alt="Onliner" title="Onliner"></a>
        <a href="http://husse.by" target="_blank"><img src="~/Images/logos/husse.png" alt="Husse" title="Husse"></a>
        <a href="http://www.doctor-vet.by" target="_blank"><img src="~/Images/logos/dv.png" alt="Доктор Вет" title="Доктор Вет"></a>
        <a href="http://lovelypets.by" target="_blank"><img src="~/Images/logos/lovelypets.png" alt="Lovely Pets" title="Lovely Pets"></a>
        <a href="http://alfavet.by" target="_blank"><img src="~/Images/logos/alfavet.png" alt="Альфа-Вет" title="Альфа-Вет"></a>
        <a href="http://ecovet.by" target="_blank"><img src="~/Images/logos/ecovet.png" alt="ЭкоВетКом" title="ЭкоВетКом"></a>
        <a href="http://tb.by" target="_blank"><img src="~/Images/logos/tb.png" alt="Технобанк" title="Технобанк"></a>
    </nav>
</section>